stripe_api_key: "sk_test_9A5wetTHxIWbS0HsAd4YgaS4"
db_dev_username: "sahild"
db_dev_password: "amrata"
AWS_ACCESS_KEY_ID: "AKIAJFUH2NEYXWZ7WASQ"
AWS_SECRET_ACCESS_KEY: "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"
AWS_BUCKET: "testbucket"
facebook_app_id: "741217782580221"
facebook_app_secret: "38f28136f0afa04a1e638b39f2ebf608"
google_client_secret: "sPLUfzVmR-EnXbmIfBxwBkDp"
google_client_id: "830393760773-plbl2hqmdtq810rn3invets0722r4lqj.apps.googleusercontent.com"
twitter_api_key: "WVTmEQTEbXqDVbJzgdI8Y5r9r"
twitter_api_secret: "ODqP4z6AGzY6CEiyq5YYNhTR5KvrNlftZETkPMiTOtYis3rzP9"
linkedin_api_key: "75xrgl8hzpymce"
linkedin_secret_key: "QOmnlIRE6Pezo00J"
