stripe_api_key: "sk_test_9A5wetTHxIWbS0HsAd4YgaS4"
db_dev_username: "sahild"
db_dev_password: "amrata"
AWS_ACCESS_KEY_ID: "AKIAJFUH2NEYXWZ7WASQ"
AWS_SECRET_ACCESS_KEY: "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"
AWS_BUCKET: "testbucket"
